type HEX = string;

const WHITE: HEX = "#FFFFFF";
const BLACK: HEX = "#000000";
const RED: HEX = "#FF0000";
const GREEN: HEX = "#00FF00";
const BLUE: HEX = "#0000FF";
const YELLOW: HEX = "#FFFF00";
const PINK: HEX = "#C9A0DC";
const PURPLE: HEX = "#680994";
const GRAY_PURPLE: HEX = "#535055";
const DARK_PURPLE: HEX = "#3E0559";

const QUIZ_DARK_PURPLE: HEX = "#471A42";
const QUIZ_YELLOW: HEX = "#EFA929";
const QUIZ_BLUE: HEX = "#2C70AE";
const QUIZ_RED: HEX = "#D4546D";
const QUIZ_CYAN: HEX = "#2E9DA6";
const QUIZ_CORRECT_GREEN: HEX = "#6BAE44";
const QUIZ_WRONG_RED: HEX = "#F22F3A";

const COLORS = {
    WHITE, BLACK, RED, GREEN, BLUE, YELLOW, PINK, PURPLE, GRAY_PURPLE, DARK_PURPLE,
    QUIZ_DARK_PURPLE, QUIZ_YELLOW, QUIZ_BLUE, QUIZ_RED, QUIZ_CYAN, QUIZ_CORRECT_GREEN, QUIZ_WRONG_RED
};

export default COLORS;
